name: rstudio-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git  #==2.51.0
  - ipython==9.7.0
  - jupyter-resource-usage=1.2.0
  - jupyterhub==5.4.3
  - jupyterlab==4.5.2
  - jupyter-archive==3.4.0
  - jupyter_server==2.17.0
  - jupyterlab-git==0.51.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.5.0
  - python==3.12.*
  - pip==25.1.1
  - regex==2025.11.3
  - sqlite==3.51.1

  # r2d installs jupyter-rsession-proxy, but in the base python env, not in the updated one
  - jupyter-rsession-proxy==2.3.0

  # vscode
  - code-server==4.106.2
  - jupyter-vscode-proxy==0.7
  - jupyter-server-proxy==4.4.0

  # jupyterbook
  - mystmd==1.3.28

  # gh-scoped-creds needs a newer version of git than what jammy provides
  - gh-scoped-creds==4.1

  # pip installed packages, conda is preferred
  - pip:
    # r2d installs jupyter-shiny-proxy, but in the base python env, not in the updated one
    - jupyter-shiny-proxy==1.3
    - nbconvert[webpdf]==7.16.6
    - otter-grader==6.1.3
